export const REQUEST_PAYMENT = "payment/REQUEST_PAYMENT";
export const REQUEST_SUCCESS_TODAY_LESSON =
    "payment/REQUEST_SUCCESS_TODAY_LESSON";
export const REQUEST_FAILURE_PAYMENT = "payment/REQUEST_FAILURE_PAYMENT";
export const REQUEST_PAYMENT_ONE = "payment/REQUEST_PAYMENT_ONE";

export const REQUEST_SUCCESS_TODAY_PAYMENT =
    "payment/REQUEST_SUCCESS_TODAY_PAYMENT";

export const UPDATE_PAYMENT = "payment/UPDATE_PAYMENT";
