export const UPDATE_PAYMENT_STATUS = "payment/UPDATE_PAYMENT_STATUS";
export const UPDATE_DATE = "payment/UPDATE_DATE";

export const REQUEST_DAY_LESSON_PAYMENT = "payment/REQUEST_DAY_LESSON_PAYMENT";
export const REQUEST_FAILURE = "payment/REQUEST_FAILURE";
export const REQUEST_SUCCESS_DAY_LESSON = "payment/REQUEST_SUCCESS_DAY_LESSON";

export const REQUEST_LESSON_PAYMENT = "payment/REQUEST_LESSON_PAYMENT";
export const REQUEST_LESSON_PAYMENT_SUCCESS =
    "payment/REQUEST_LESSON_PAYMENT_SUCCESS";

export const SELECT_LESSON = "payment/SELECT_LESSON";
