import React, { useState } from "react";
import { handleActions, createAction } from "redux-actions";
import { useSelector } from "react-redux";

const SELECT_ALL = "SELECT_ALL";
const CHANGE_ATT = "CHANGE_ATT";

export const selectAll = createAction(SELECT_ALL);
export const changeAtt = createAction(CHANGE_ATT);

//

const initState = {
    originAttendances: {
        //key => lesson's key value, value => members
        1: [
            //lesson's key
            {
                id: 1,
                // member's key
                name: "Jon",
                1: "결석",
                2: "결석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
        ],
        2: [
            {
                id: 2,
                name: "Cersei",
                1: "결석",
                2: "결석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
            {
                id: 3,
                name: "Jaime",
                1: "결석",
                2: "결석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
        ],
        3: [
            {
                id: 4,
                name: "Arya",
                1: "결석",
                2: "결석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
            {
                id: 5,
                name: "Daenerys",
                1: "결석",
                2: "결석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
            {
                id: 6,
                name: "null",
                1: "결석",
                2: "결석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
        ],
        4: [
            {
                id: 7,
                name: "Ferrara",
                1: "결석",
                2: "결석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
            {
                id: 8,
                name: "Rossini",
                1: "결석",
                2: "결석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
            {
                id: 9,
                name: "Harvey",
                1: "결석",
                2: "결석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
            {
                id: 10,
                name: "Harvey1",
                1: "결석",
                2: "결석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
        ],
        5: [
            {
                id: 11,
                name: "Ferrara8",
                1: "결석",
                2: "결석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
            {
                id: 12,
                name: "Rossini8",
                1: "결석",
                2: "출석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
            {
                id: 13,
                name: "Harve8",
                1: "결석",
                2: "결석",
                3: "결석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
            {
                id: 14,
                name: "Harvey8",
                1: "결석",
                2: "결석",
                3: "출석",
                4: "결석",
                5: "결석",
                6: "결석",
                7: "결석",
                8: "결석",
                9: "결석",
                10: "결석",
                11: "결석",
                12: "결석",
            },
        ],
    },
    selected: [],
};

const attendanceReducer = handleActions(
    {
        [SELECT_ALL]: (state, action) => ({
            ...state,
        }),
        [CHANGE_ATT]: (state, action) => ({
            ...state,
            originAttendances: {
                ...state.originAttendances,
                // action.payload.lessonId
            },
        }),
    },
    initState
);

export default attendanceReducer;
