export const UPDATE_ATT_STATUS = "attendance/UPDATE_ATT_STATUS";
export const UPDATE_DATE = "attendance/UPDATE_DATE";

export const REQUEST_DAY_LESSON = "attendance/REQUEST_DAY_LESSON";
export const REQUEST_FAILURE = "attendance/REQUEST_FAILURE";
export const REQUEST_SUCCESS_DAY_LESSON = "attendance/REQUEST_SUCCESS_DAY_LESSON";

export const REQUEST_LESSON_ATTENDANCE = "attendance/REQUEST_LESSON_ATTENDANCE";
export const REQUEST_LESSON_ATTENDANCE_SUCCESS = "attendance/REQUEST_LESSON_ATTENDANCE_SUCCESS";

export const SELECT_LESSON = "attendance/SELECT_LESSON";